name: Test

on:
  push:
    branches: [ 'main', 'v*' ]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1

      - name: Run Tests
        run: |
          yarn install --frozen-lockfile
          yarn run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info